### ISSUE TITLE
Close action vs decline button in notification

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/notifications#22]
When you have a remote share, there’s both a decline button and a close X action on the top right.

What’s the relevance of the X action on the top right? What happens when I click it? If it’s the same as decline, we should not show it, as it’s not sure what happens when clicked. Either you accept or decline the share.

@nickvergessen @PVince81 can you fix that?

**Comment by nickvergessen** [comment]
The X on notifications is dismiss, it just deletes the notification, nothing more.

**Comment by jancborchardt** [comment]
Well … what happens then to a share? It’s declined, right?

**Comment by nickvergessen** [comment]
No, it's left in place, still to accept/decline.

**Comment by jancborchardt** [comment]
What do you mean, it’s left in place? I thought it’s dismissing it? Will it come up again on refresh, or what happens then?

**Comment by nickvergessen** [comment]
The notification is dismissed and deleted
The remote share request is still there and unhandled

Refreshing and polling will not bring back the notification.

**Comment by jancborchardt** [comment]
Ok, so clearly this is a confusion and pressing the x results in an unresolved state. When you press the close x on the remote sharing modal, it comes back on next refresh, which is ok.

For the notification, there should be no close x in this case. Either you have to accept or decline the share. There is no other option.

**Comment by nickvergessen** [comment]
Well we need it for notifications that don't have actions, otherwise you can't get ride of them. But maybe we only add it to those then.

On the other hand we need a "what when notifications app is disabled" path for the remote share solution anyway. Because having to enable notifications app to receive remote shares is :hankey:  UX.
And when there is another page where you can accept the shares, dismissing them is okay again. You dismiss the alarm, doesn't mean you want to deal with the content right now?

**Comment by jancborchardt** [comment]
> Well we need it for notifications that don't have actions, otherwise you can't get ride of them. But maybe we only add it to those then.

Exactly.

> On the other hand we need a "what when notifications app is disabled" path for the remote share solution anyway.

https://github.com/owncloud/core/issues/13495

**Comment by nickvergessen** [comment]
Closing as per above and Notifications planning meeting from yesterday.
