### ISSUE TITLE
remote-share notification: Add size information

### ISSUE THREAD

**Issue by dragotin** [owncloud/notifications#73]
Please add the overall size of the new share to the notification.

The clients can and should use this information to enable selective sync based on the size info.

**Comment by nickvergessen** [comment]
The notification app does not know anything like shares or has even any additional information available.

Theory away: the size could change between initiating remote share and the recipient reading the notification. And then we would display false information.

So closing as "out of scope" for the notification app. If you really think this is needed, feel free to open a new issue in core. However we didn't have a size in that windows on the server since ever. And I don't think we can do a lot about it.

**Comment by dragotin** [comment]
Yes, for sure you do not have a size in that window. And you do not need it because you do not flood the harddisk of the whatever client device the user might have. We **need** the size to destinguish if we will sync it or not by default.

**Comment by nickvergessen** [comment]
When the user accepts via the UI it might also get flooded to the disk, so there is not really a difference.
The normal discovery and the "500 MB folder size" rule should take care of this, I think.

**Comment by dragotin** [comment]
Yes, of course it does, but that is two user actions which no user understands. We need to combine that on the clients: *Accept the share Yes/No* plus *Sync the share Yes/No*
